# This Dockerfile is designed to test error paths in index.js
# Don't model anything after this :)

CMD ["test"]
FROM ubuntu
FROM ubuntu:latest
this is not a command

MAINTAINER test

ADD
RUN sudo rm /tmp/1
RUN apt-get upgrade
RUN apt-get install python
RUN apt-get dist-upgrade
RUN apt-get update -y
RUN apk add python-pip
RUN apk add --no-cache python-dev build-base wget && apk del python-dev build-base wget

EXPOSE 80a
EXPOSE 80:80
VOLUME /tmp
ENV testsomething=test valuye
LABEL test test
COPY ./test /tmp
USER ubuntu ubuntu
WORKDIR in valid
ARG test
ONBUILD RUN echo test
STOPSIGNAL SIGKILL
ADD /test* /test2
CMD ["bash"]
SHELL ["/bin/sh", "-c"]
ENTRYPOINT ["bash"]
